renew:
  name: Renew loans
  description: >
    Target a book sensor to renew that item, or the account calendar to renew all loans for that account.
  target:
    entity:
      - domain: calendar
        integration: lissy
      - domain: sensor
        integration: lissy
