renew:
  name: Renew loans
  description: >
    Target a book sensor to renew that item, or the Lissy device to renew all loans for that account.
  target:
    entity:
      - domain: sensor
        integration: lissy
